### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tapio-salonen** [jpasikainen/ot-harjoitustyo#1]
## Koodin laatu
Koodi vaikuttaa omaan silmään yllättävän laadukkaalta ja minulla ei ole siltä osin sen laatuun parannusehdotuksia, mutta ylipäätänsä hieman mainintoja:

Metodien ja muuttujen nimeäminen on mielestäni onnistunutta. Muuttujien ja metodien nimet kuvastavat hyvin sitä mitä tekevät. Koodia tarkastelevan on helppo ymmärtää koodia, osin myös javadocin kautta.

Testien nimentä vaikuttaa järkevältä ja testien nimet kertovat hyvin sitä mitä ohjelman osaa ne testaavat. Ohjelman kokoon nähden testejä on riittävästi ja testikattavuus on hyvä.

Sovelluslogiikka on mielestäni hyvin eroitettu käyttöliittymästä. Käyttöliittymä ja sovelluslogiikka sisältävät lyhyehköjä metodeja molemmat ja niitä on täten helppo lukea. Ohjelma ei myöskään sisällä liikaa toisteista koodia mikä on hyvä asia.

Ohjelman normaalilla käytöllä sovellus ei kaadu ja en huomannut selkeitä rikkinäisyyksiä ajaessanin ohjelmaa.

## Parannusehdotuksia:

Kiinnitin erityisesti huomiota repositoriossa olevaan tietokantaan. Voisiko tämän tietokannan esimerkiksi luoda sovelluksen mahdollisen asennuksen yhteydessä tai jos peli huomaa, että tietokantaa ei löydy, niin alustaa uuden tietokannan sovellukselle. Nyt käy nimittäin tilanne, että jos tietokanta poistetaan ennen sovelluksen käynnistämistä, niin sovellus kyllä käynnistyy, mutta käyttäjä saa konsoliin stack trace erroreita kun hän yrittää viljellä. Vaihtoehtoisesti käyttäjälle voitasiin antaa ilmoitus mikäli peli ei tietokantaa löydä ja tällöin peliä ei voisi pelata ennen kuin tietokanta lisätään. Lisäksi repositorion siisteyden kannalta tietokannasta olisi hyvä päästä eroon. Ilman tietokantaa myös kolme dao testeistä epäonnistuu ja antaa virhettä.

Pelin main luokka Game.java on nyt sovelluslogiikan pakkauksessa vaikka se sisältää käyttöliittymän javafx importteja. Main luokalla ei vaikuta olevan selvää yhteyttä sovelluslogiikkaan, muuta kuin että se käynnitää luokan GameManager. Mainin voisi esimerkiksi siirtää omaan pakkaukseensa.

Ohjelman dao luokille on tehty rajapinnat, joka on hyvä asia. Voisiko sovelluslogiikka kenties käyttää muuttujina dao luokkien sijasta olemassa olevia rajapintoja? Tämä vaatisi hiukan refaktorointia, mutta tekisi selkeämmäksi sen että sovelluslogiikka varmasti käyttää rajapinnassa määriteltyjä metodeja.

**Comment by jpasikainen** [comment]
Kiitos parannusehdotuksista :+1:
